<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 10/20/17
 * Time: 5:25 PM
 */

namespace execut\shops;


use execut\dependencies\PluginBehavior;
use execut\navigation\Page;

/**
 * Class Module
 * @package execut\shops
 * @mixin PluginBehavior
 */
class Module extends \yii\base\Module implements Plugin
{
    public function behaviors()
    {
        return [
            'dependencies' => [
                'class' => PluginBehavior::class,
                'pluginInterface' => Plugin::class,
            ],
        ]; // TODO: Change the autogenerated stub
    }

    public function getShopsFieldsPlugins() {
        $result = $this->getPluginsResults(__FUNCTION__);
        if ($result === null) {
            $result = [];
        }

        return $result;
    }

    public function getNavigationPageByShopModel($model) {
        $result = $this->getPluginsResults(__FUNCTION__, true, func_get_args());
        if (!$result) {
            $result = new Page([
                'name' => $model->name,
            ]);
        }

        return $result;
    }
}